language: node_js
before_install:
  - chmod 777 deploy.sh
sudo: required
node_js:
  - 'lts/*'
cache:
  directories:
    - node_modules
  yarn: true
script:
  - ./deploy.sh
branch: master
env:
  global:
    - U_EMILE: 1029363172@qq.com
    - U_NAME: Yuhn-z
